"""
Pipeline 5: Excel Export Agent
Builds a DCF scaffold from extracted financial signals using openpyxl.
Outputs a timestamped Excel file per company per filing cycle.
"""

import logging
import os
from datetime import datetime, timezone
from typing import Optional

import openpyxl
from openpyxl.styles import (
    Alignment, Border, Font, PatternFill, Side
)
from openpyxl.utils import get_column_letter
from sqlalchemy import text

from app.db.database import get_db

logger = logging.getLogger(__name__)

EXPORTS_DIR = "exports"


# ---------------------------------------------------------------------------
# Style helpers
# ---------------------------------------------------------------------------

def _header_font() -> Font:
    return Font(name="Calibri", bold=True, color="FFFFFF", size=11)


def _header_fill() -> PatternFill:
    return PatternFill(fill_type="solid", fgColor="1F4E79")


def _subheader_fill() -> PatternFill:
    return PatternFill(fill_type="solid", fgColor="2E75B6")


def _accent_fill() -> PatternFill:
    return PatternFill(fill_type="solid", fgColor="D6E4F0")


def _thin_border() -> Border:
    side = Side(style="thin", color="BFBFBF")
    return Border(left=side, right=side, top=side, bottom=side)


def _apply_header(cell, text: str, fill=None) -> None:
    cell.value = text
    cell.font = _header_font()
    cell.fill = fill or _header_fill()
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    cell.border = _thin_border()


def _apply_label(cell, text: str) -> None:
    cell.value = text
    cell.font = Font(name="Calibri", bold=True, size=10)
    cell.alignment = Alignment(horizontal="left", vertical="center")
    cell.border = _thin_border()


def _apply_value(cell, value, number_format: str = "#,##0.00") -> None:
    cell.value = value
    cell.font = Font(name="Calibri", size=10)
    cell.number_format = number_format
    cell.alignment = Alignment(horizontal="right", vertical="center")
    cell.border = _thin_border()


def _apply_accent(cell) -> None:
    cell.fill = _accent_fill()


# ---------------------------------------------------------------------------
# Sheet builders
# ---------------------------------------------------------------------------

def _build_summary_sheet(ws, ticker: str, extraction: dict, filing_meta: dict) -> None:
    """Cover sheet: company overview and filing metadata."""
    ws.title = "Summary"
    ws.column_dimensions["A"].width = 30
    ws.column_dimensions["B"].width = 50

    # Title block
    ws.merge_cells("A1:B1")
    title_cell = ws["A1"]
    title_cell.value = f"Financial Filing Intelligence Report — {ticker}"
    title_cell.font = Font(name="Calibri", bold=True, size=14, color="FFFFFF")
    title_cell.fill = _header_fill()
    title_cell.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 30

    ws.merge_cells("A2:B2")
    subtitle = ws["A2"]
    subtitle.value = "Generated by Datawebify | filings.datawebify.com"
    subtitle.font = Font(name="Calibri", italic=True, size=10, color="595959")
    subtitle.alignment = Alignment(horizontal="center")

    # Metadata rows
    meta_rows = [
        ("Ticker", ticker),
        ("Company", filing_meta.get("company_name", "N/A")),
        ("Filing Type", filing_meta.get("filing_type", "N/A")),
        ("Filing Date", filing_meta.get("filing_date", "N/A")),
        ("Report Generated", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")),
        ("Going Concern Flag", "YES" if extraction.get("going_concern_flag") else "NO"),
    ]

    for i, (label, value) in enumerate(meta_rows, start=4):
        _apply_label(ws.cell(row=i, column=1), label)
        cell = ws.cell(row=i, column=2)
        cell.value = str(value)
        cell.font = Font(name="Calibri", size=10)
        cell.border = _thin_border()
        if label == "Going Concern Flag" and value == "YES":
            cell.font = Font(name="Calibri", size=10, color="FF0000", bold=True)


def _build_dcf_sheet(ws, ticker: str, extraction: dict) -> None:
    """DCF scaffold with revenue, capex, and WACC assumptions."""
    ws.title = "DCF Model"
    ws.column_dimensions["A"].width = 32
    for col in ["B", "C", "D", "E", "F"]:
        ws.column_dimensions[col].width = 16

    years = ["Year 1", "Year 2", "Year 3", "Year 4", "Year 5"]

    # Header row
    _apply_header(ws["A1"], "DCF SCAFFOLD — " + ticker)
    for i, yr in enumerate(years, start=2):
        _apply_header(ws.cell(row=1, column=i), yr)

    # --- Revenue section ---
    ws.merge_cells("A2:F2")
    ws["A2"].value = "REVENUE INPUTS"
    ws["A2"].font = Font(name="Calibri", bold=True, size=10, color="FFFFFF")
    ws["A2"].fill = _subheader_fill()
    ws["A2"].alignment = Alignment(horizontal="left")

    capex_guidance = extraction.get("capex_guidance") or {}
    guidance_amount = capex_guidance.get("amount") if isinstance(capex_guidance, dict) else None

    revenue_rows = [
        ("Base Revenue (extracted/manual, $M)", guidance_amount or 0),
        ("Revenue Growth Rate (%)", 0.05),
        ("Projected Revenue ($M)", None),
    ]

    row = 3
    for label, base_val in revenue_rows:
        _apply_label(ws.cell(row=row, column=1), label)
        for col in range(2, 7):
            cell = ws.cell(row=row, column=col)
            if label == "Projected Revenue ($M)":
                prev_col = get_column_letter(col - 1) if col > 2 else None
                if col == 2:
                    formula = f"=B3*(1+B4)"
                else:
                    prev = get_column_letter(col - 1)
                    formula = f"={prev}{row-1}*(1+{get_column_letter(col)}4)"
                _apply_value(cell, formula if col > 2 else f"=B3*(1+B4)")
            else:
                _apply_value(cell, base_val if col == 2 else None)
            _apply_accent(cell)
        row += 1

    # --- Capex section ---
    row += 1
    ws.merge_cells(f"A{row}:F{row}")
    ws[f"A{row}"].value = "CAPEX INPUTS"
    ws[f"A{row}"].font = Font(name="Calibri", bold=True, size=10, color="FFFFFF")
    ws[f"A{row}"].fill = _subheader_fill()
    ws[f"A{row}"].alignment = Alignment(horizontal="left")
    row += 1

    capex_rows = [
        ("Capex ($M)", guidance_amount or 0),
        ("Capex as % of Revenue", 0.08),
        ("D&A ($M)", 0),
    ]
    for label, base_val in capex_rows:
        _apply_label(ws.cell(row=row, column=1), label)
        for col in range(2, 7):
            cell = ws.cell(row=row, column=col)
            _apply_value(cell, base_val if col == 2 else None)
        row += 1

    # --- FCF section ---
    row += 1
    ws.merge_cells(f"A{row}:F{row}")
    ws[f"A{row}"].value = "FREE CASH FLOW"
    ws[f"A{row}"].font = Font(name="Calibri", bold=True, size=10, color="FFFFFF")
    ws[f"A{row}"].fill = _subheader_fill()
    ws[f"A{row}"].alignment = Alignment(horizontal="left")
    row += 1

    fcf_rows = [
        ("EBIT Margin (%)", 0.20),
        ("Tax Rate (%)", 0.21),
        ("NOPAT ($M)", None),
        ("Less: Capex ($M)", None),
        ("Plus: D&A ($M)", None),
        ("Free Cash Flow ($M)", None),
    ]
    for label, base_val in fcf_rows:
        _apply_label(ws.cell(row=row, column=1), label)
        for col in range(2, 7):
            cell = ws.cell(row=row, column=col)
            _apply_value(cell, base_val if col == 2 else None)
        row += 1

    # --- WACC / Terminal Value section ---
    row += 1
    ws.merge_cells(f"A{row}:F{row}")
    ws[f"A{row}"].value = "WACC & TERMINAL VALUE"
    ws[f"A{row}"].font = Font(name="Calibri", bold=True, size=10, color="FFFFFF")
    ws[f"A{row}"].fill = _subheader_fill()
    ws[f"A{row}"].alignment = Alignment(horizontal="left")
    row += 1

    wacc_rows = [
        ("WACC (%)", 0.10),
        ("Terminal Growth Rate (%)", 0.025),
        ("Terminal Value ($M)", None),
        ("PV of Terminal Value ($M)", None),
        ("Enterprise Value ($M)", None),
    ]
    for label, base_val in wacc_rows:
        _apply_label(ws.cell(row=row, column=1), label)
        for col in range(2, 7):
            cell = ws.cell(row=row, column=col)
            _apply_value(cell, base_val if col == 2 else None)
        row += 1


def _build_signals_sheet(ws, extraction: dict) -> None:
    """Extracted financial signals from GPT-4o."""
    ws.title = "Filing Signals"
    ws.column_dimensions["A"].width = 30
    ws.column_dimensions["B"].width = 60

    _apply_header(ws["A1"], "SIGNAL TYPE")
    _apply_header(ws["B1"], "EXTRACTED VALUE")
    ws.row_dimensions[1].height = 22

    signals = [
        ("Going Concern Flag", str(extraction.get("going_concern_flag", False))),
        ("Capital Structure Changes", str(extraction.get("capital_structure_changes", "None"))),
        ("Contract Awards", str(extraction.get("contract_awards", "None"))),
        ("Capex Guidance", str(extraction.get("capex_guidance", "None"))),
        ("Undisclosed Counterparties", str(extraction.get("undisclosed_counterparties", "None"))),
    ]

    for i, (signal, value) in enumerate(signals, start=2):
        _apply_label(ws.cell(row=i, column=1), signal)
        cell = ws.cell(row=i, column=2)
        cell.value = value
        cell.font = Font(name="Calibri", size=10)
        cell.alignment = Alignment(wrap_text=True, vertical="top")
        cell.border = _thin_border()
        ws.row_dimensions[i].height = 40


# ---------------------------------------------------------------------------
# Main export function
# ---------------------------------------------------------------------------

def build_dcf_export(ticker: str, filing_id: Optional[str] = None) -> dict:
    """
    Fetch the latest extraction for a ticker, build DCF scaffold, save to exports/.
    If filing_id is provided, use that specific filing.
    Returns a dict with file path and status.
    """
    os.makedirs(EXPORTS_DIR, exist_ok=True)
    db = next(get_db())

    try:
        # Fetch latest extraction for ticker
        if filing_id:
            query = """
                SELECT
                    e.capital_structure_changes,
                    e.contract_awards,
                    e.capex_guidance,
                    e.going_concern_flag,
                    e.undisclosed_counterparties,
                    r.ticker,
                    r.company_name,
                    r.filing_type,
                    r.filed_date,
                    r.id
                FROM filings_extractions e
                JOIN filings_raw r ON r.id = e.filing_id
                WHERE r.ticker = :ticker AND r.id = :filing_id
                LIMIT 1
            """
            row = db.execute(text(query), {"ticker": ticker, "filing_id": filing_id}).fetchone()
        else:
            query = """
                SELECT
                    e.capital_structure_changes,
                    e.contract_awards,
                    e.capex_guidance,
                    e.going_concern_flag,
                    e.undisclosed_counterparties,
                    r.ticker,
                    r.company_name,
                    r.filing_type,
                    r.filed_date,
                    r.id
                FROM filings_extractions e
                JOIN filings_raw r ON r.id = e.filing_id
                WHERE r.ticker = :ticker
                ORDER BY r.filed_date DESC
                LIMIT 1
            """
            row = db.execute(text(query), {"ticker": ticker}).fetchone()

        if not row:
            return {"success": False, "error": f"No extraction found for ticker {ticker}"}

        (
            capital_structure_changes,
            contract_awards,
            capex_guidance,
            going_concern_flag,
            undisclosed_counterparties,
            db_ticker,
            company_name,
            filing_type,
            filing_date,
            db_filing_id
        ) = row

        import json

        def _parse(val):
            if isinstance(val, str):
                try:
                    return json.loads(val)
                except Exception:
                    return val
            return val or {}

        extraction = {
            "capital_structure_changes": _parse(capital_structure_changes),
            "contract_awards": _parse(contract_awards),
            "capex_guidance": _parse(capex_guidance),
            "going_concern_flag": going_concern_flag or False,
            "undisclosed_counterparties": _parse(undisclosed_counterparties),
        }

        filing_meta = {
            "company_name": company_name or ticker,
            "filing_type": filing_type or "N/A",
            "filing_date": str(filing_date) if filing_date else "N/A",
        }

        # Build workbook
        wb = openpyxl.Workbook()
        wb.remove(wb.active)  # Remove default sheet

        ws_summary = wb.create_sheet("Summary")
        ws_dcf = wb.create_sheet("DCF Model")
        ws_signals = wb.create_sheet("Filing Signals")

        _build_summary_sheet(ws_summary, ticker, extraction, filing_meta)
        _build_dcf_sheet(ws_dcf, ticker, extraction)
        _build_signals_sheet(ws_signals, extraction)

        # Save with timestamp
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        filename = f"{ticker}_DCF_{timestamp}.xlsx"
        filepath = os.path.join(EXPORTS_DIR, filename)
        wb.save(filepath)

        logger.info(f"DCF export saved: {filepath}")
        return {
            "success": True,
            "file": filepath,
            "ticker": ticker,
            "filing_id": str(db_filing_id),
            "company": filing_meta["company_name"],
            "filing_type": filing_meta["filing_type"],
            "filing_date": filing_meta["filing_date"],
        }

    except Exception as e:
        logger.error(f"DCF export failed for {ticker}: {e}")
        return {"success": False, "error": str(e)}

    finally:
        db.close()


def run_excel_pipeline(tickers: list) -> dict:
    """
    Run DCF export for a list of tickers.
    Returns summary of results.
    """
    results = {"exported": 0, "failed": 0, "files": []}

    for ticker in tickers:
        result = build_dcf_export(ticker)
        if result.get("success"):
            results["exported"] += 1
            results["files"].append(result["file"])
        else:
            results["failed"] += 1
            logger.error(f"Export failed for {ticker}: {result.get('error')}")

    return results